version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "checkSQS"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-icc46jh6nvkb"
s3_prefix = "checkSQS"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
